version: '3.8'

services:
  agave-db:
    image: postgres:16-alpine
    container_name: agave_postgres
    environment:
      POSTGRES_DB: agave_erp
      POSTGRES_USER: agave_admin
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_v2:
